// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart_items.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (
  cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
`

type CreateCartItemParams struct {
	CartID               int32       `db:"cart_id" json:"cart_id"`
	ProductID            int32       `db:"product_id" json:"product_id"`
	Quantity             int32       `db:"quantity" json:"quantity"`
	Price                int32       `db:"price" json:"price"`
	PurchaseType         string      `db:"purchase_type" json:"purchase_type"`
	SubscriptionInterval pgtype.Text `db:"subscription_interval" json:"subscription_interval"`
	StripePriceID        string      `db:"stripe_price_id" json:"stripe_price_id"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItems, error) {
	row := q.db.QueryRow(ctx, createCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.PurchaseType,
		arg.SubscriptionInterval,
		arg.StripePriceID,
	)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const deleteCartItemByProductAndType = `-- name: DeleteCartItemByProductAndType :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2 AND purchase_type = $3 AND (subscription_interval = $4 OR ($4 IS NULL AND subscription_interval IS NULL))
`

type DeleteCartItemByProductAndTypeParams struct {
	CartID               int32       `db:"cart_id" json:"cart_id"`
	ProductID            int32       `db:"product_id" json:"product_id"`
	PurchaseType         string      `db:"purchase_type" json:"purchase_type"`
	SubscriptionInterval pgtype.Text `db:"subscription_interval" json:"subscription_interval"`
}

func (q *Queries) DeleteCartItemByProductAndType(ctx context.Context, arg DeleteCartItemByProductAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemByProductAndType,
		arg.CartID,
		arg.ProductID,
		arg.PurchaseType,
		arg.SubscriptionInterval,
	)
	return err
}

const deleteCartItemByProductID = `-- name: DeleteCartItemByProductID :exec
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemByProductIDParams struct {
	CartID    int32 `db:"cart_id" json:"cart_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

func (q *Queries) DeleteCartItemByProductID(ctx context.Context, arg DeleteCartItemByProductIDParams) error {
	_, err := q.db.Exec(ctx, deleteCartItemByProductID, arg.CartID, arg.ProductID)
	return err
}

const getCartItem = `-- name: GetCartItem :one

SELECT id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
FROM cart_items
WHERE id = $1
`

// internal/database/queries/cart_items.sql
func (q *Queries) GetCartItem(ctx context.Context, id int32) (CartItems, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemByProductAndType = `-- name: GetCartItemByProductAndType :one
SELECT id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
FROM cart_items
WHERE cart_id = $1 AND product_id = $2 AND purchase_type = $3 AND (subscription_interval = $4 OR ($4 IS NULL AND subscription_interval IS NULL))
`

type GetCartItemByProductAndTypeParams struct {
	CartID               int32       `db:"cart_id" json:"cart_id"`
	ProductID            int32       `db:"product_id" json:"product_id"`
	PurchaseType         string      `db:"purchase_type" json:"purchase_type"`
	SubscriptionInterval pgtype.Text `db:"subscription_interval" json:"subscription_interval"`
}

func (q *Queries) GetCartItemByProductAndType(ctx context.Context, arg GetCartItemByProductAndTypeParams) (CartItems, error) {
	row := q.db.QueryRow(ctx, getCartItemByProductAndType,
		arg.CartID,
		arg.ProductID,
		arg.PurchaseType,
		arg.SubscriptionInterval,
	)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemByProductID = `-- name: GetCartItemByProductID :one
SELECT id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
FROM cart_items
WHERE cart_id = $1 AND product_id = $2
LIMIT 1
`

type GetCartItemByProductIDParams struct {
	CartID    int32 `db:"cart_id" json:"cart_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

func (q *Queries) GetCartItemByProductID(ctx context.Context, arg GetCartItemByProductIDParams) (CartItems, error) {
	row := q.db.QueryRow(ctx, getCartItemByProductID, arg.CartID, arg.ProductID)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemCount = `-- name: GetCartItemCount :one
SELECT COALESCE(SUM(quantity), 0)::integer as item_count
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) GetCartItemCount(ctx context.Context, cartID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getCartItemCount, cartID)
	var item_count int32
	err := row.Scan(&item_count)
	return item_count, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.price, ci.purchase_type, ci.subscription_interval, ci.stripe_price_id, ci.created_at,
       p.name as product_name, p.description as product_description, p.stock as product_stock
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC
`

type GetCartItemsRow struct {
	ID                   int32       `db:"id" json:"id"`
	CartID               int32       `db:"cart_id" json:"cart_id"`
	ProductID            int32       `db:"product_id" json:"product_id"`
	Quantity             int32       `db:"quantity" json:"quantity"`
	Price                int32       `db:"price" json:"price"`
	PurchaseType         string      `db:"purchase_type" json:"purchase_type"`
	SubscriptionInterval pgtype.Text `db:"subscription_interval" json:"subscription_interval"`
	StripePriceID        string      `db:"stripe_price_id" json:"stripe_price_id"`
	CreatedAt            time.Time   `db:"created_at" json:"created_at"`
	ProductName          string      `db:"product_name" json:"product_name"`
	ProductDescription   pgtype.Text `db:"product_description" json:"product_description"`
	ProductStock         int32       `db:"product_stock" json:"product_stock"`
}

func (q *Queries) GetCartItems(ctx context.Context, cartID int32) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.PurchaseType,
			&i.SubscriptionInterval,
			&i.StripePriceID,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductDescription,
			&i.ProductStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemsByProduct = `-- name: GetCartItemsByProduct :many
SELECT id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type GetCartItemsByProductParams struct {
	CartID    int32 `db:"cart_id" json:"cart_id"`
	ProductID int32 `db:"product_id" json:"product_id"`
}

func (q *Queries) GetCartItemsByProduct(ctx context.Context, arg GetCartItemsByProductParams) ([]CartItems, error) {
	rows, err := q.db.Query(ctx, getCartItemsByProduct, arg.CartID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItems{}
	for rows.Next() {
		var i CartItems
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.PurchaseType,
			&i.SubscriptionInterval,
			&i.StripePriceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemsByPurchaseType = `-- name: GetCartItemsByPurchaseType :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.price, ci.purchase_type, ci.subscription_interval, ci.stripe_price_id, ci.created_at,
       p.name as product_name, p.description as product_description, p.stock as product_stock
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
WHERE ci.cart_id = $1 AND ci.purchase_type = $2
ORDER BY ci.created_at ASC
`

type GetCartItemsByPurchaseTypeParams struct {
	CartID       int32  `db:"cart_id" json:"cart_id"`
	PurchaseType string `db:"purchase_type" json:"purchase_type"`
}

type GetCartItemsByPurchaseTypeRow struct {
	ID                   int32       `db:"id" json:"id"`
	CartID               int32       `db:"cart_id" json:"cart_id"`
	ProductID            int32       `db:"product_id" json:"product_id"`
	Quantity             int32       `db:"quantity" json:"quantity"`
	Price                int32       `db:"price" json:"price"`
	PurchaseType         string      `db:"purchase_type" json:"purchase_type"`
	SubscriptionInterval pgtype.Text `db:"subscription_interval" json:"subscription_interval"`
	StripePriceID        string      `db:"stripe_price_id" json:"stripe_price_id"`
	CreatedAt            time.Time   `db:"created_at" json:"created_at"`
	ProductName          string      `db:"product_name" json:"product_name"`
	ProductDescription   pgtype.Text `db:"product_description" json:"product_description"`
	ProductStock         int32       `db:"product_stock" json:"product_stock"`
}

func (q *Queries) GetCartItemsByPurchaseType(ctx context.Context, arg GetCartItemsByPurchaseTypeParams) ([]GetCartItemsByPurchaseTypeRow, error) {
	rows, err := q.db.Query(ctx, getCartItemsByPurchaseType, arg.CartID, arg.PurchaseType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsByPurchaseTypeRow{}
	for rows.Next() {
		var i GetCartItemsByPurchaseTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.PurchaseType,
			&i.SubscriptionInterval,
			&i.StripePriceID,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductDescription,
			&i.ProductStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartTotal = `-- name: GetCartTotal :one
SELECT COALESCE(SUM(quantity * price), 0)::integer as total
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) GetCartTotal(ctx context.Context, cartID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getCartTotal, cartID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET
  quantity = $2,
  price = $3,
  stripe_price_id = $4
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
`

type UpdateCartItemParams struct {
	ID            int32  `db:"id" json:"id"`
	Quantity      int32  `db:"quantity" json:"quantity"`
	Price         int32  `db:"price" json:"price"`
	StripePriceID string `db:"stripe_price_id" json:"stripe_price_id"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItems, error) {
	row := q.db.QueryRow(ctx, updateCartItem,
		arg.ID,
		arg.Quantity,
		arg.Price,
		arg.StripePriceID,
	)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, price, purchase_type, subscription_interval, stripe_price_id, created_at
`

type UpdateCartItemQuantityParams struct {
	ID       int32 `db:"id" json:"id"`
	Quantity int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItems, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItems
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.PurchaseType,
		&i.SubscriptionInterval,
		&i.StripePriceID,
		&i.CreatedAt,
	)
	return i, err
}
