// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/lib/pq"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE deleted_at IS NULL
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByStatus = `-- name: CountProductsByStatus :one
SELECT COUNT(*) FROM products WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProductsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscribableProducts = `-- name: CountSubscribableProducts :one
SELECT COUNT(*) FROM products 
WHERE subscription_enabled = true AND status = 'published' AND deleted_at IS NULL
`

func (q *Queries) CountSubscribableProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribableProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable,
    origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level,
    flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm,
    hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata,
    subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity,
    subscription_discount_percentage, subscription_priority
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22,
    $23, $24, $25, $26, $27, $28, $29,
    $30, $31, $32, $33, $34, $35
) RETURNING id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority
`

type CreateProductParams struct {
	Title                          string           `db:"title" json:"title"`
	Handle                         string           `db:"handle" json:"handle"`
	Subtitle                       pgtype.Text      `db:"subtitle" json:"subtitle"`
	Description                    pgtype.Text      `db:"description" json:"description"`
	Thumbnail                      pgtype.Text      `db:"thumbnail" json:"thumbnail"`
	Status                         string           `db:"status" json:"status"`
	IsGiftcard                     bool             `db:"is_giftcard" json:"is_giftcard"`
	Discountable                   bool             `db:"discountable" json:"discountable"`
	OriginCountry                  pgtype.Text      `db:"origin_country" json:"origin_country"`
	Region                         pgtype.Text      `db:"region" json:"region"`
	Farm                           pgtype.Text      `db:"farm" json:"farm"`
	AltitudeMin                    pgtype.Int4      `db:"altitude_min" json:"altitude_min"`
	AltitudeMax                    pgtype.Int4      `db:"altitude_max" json:"altitude_max"`
	ProcessingMethod               pgtype.Text      `db:"processing_method" json:"processing_method"`
	RoastLevel                     pgtype.Text      `db:"roast_level" json:"roast_level"`
	FlavorNotes                    pq.StringArray   `db:"flavor_notes" json:"flavor_notes"`
	Varietal                       pgtype.Text      `db:"varietal" json:"varietal"`
	HarvestDate                    pgtype.Date      `db:"harvest_date" json:"harvest_date"`
	WeightGrams                    pgtype.Int4      `db:"weight_grams" json:"weight_grams"`
	LengthCm                       pgtype.Numeric   `db:"length_cm" json:"length_cm"`
	HeightCm                       pgtype.Numeric   `db:"height_cm" json:"height_cm"`
	WidthCm                        pgtype.Numeric   `db:"width_cm" json:"width_cm"`
	HsCode                         pgtype.Text      `db:"hs_code" json:"hs_code"`
	MidCode                        pgtype.Text      `db:"mid_code" json:"mid_code"`
	Material                       pgtype.Text      `db:"material" json:"material"`
	ExternalID                     pgtype.Text      `db:"external_id" json:"external_id"`
	ProductTypeID                  pgtype.UUID      `db:"product_type_id" json:"product_type_id"`
	CollectionID                   pgtype.UUID      `db:"collection_id" json:"collection_id"`
	Metadata                       pgtype.JSONCodec `db:"metadata" json:"metadata"`
	SubscriptionEnabled            bool             `db:"subscription_enabled" json:"subscription_enabled"`
	SubscriptionIntervals          pq.StringArray   `db:"subscription_intervals" json:"subscription_intervals"`
	MinSubscriptionQuantity        pgtype.Int4      `db:"min_subscription_quantity" json:"min_subscription_quantity"`
	MaxSubscriptionQuantity        pgtype.Int4      `db:"max_subscription_quantity" json:"max_subscription_quantity"`
	SubscriptionDiscountPercentage pgtype.Numeric   `db:"subscription_discount_percentage" json:"subscription_discount_percentage"`
	SubscriptionPriority           pgtype.Int4      `db:"subscription_priority" json:"subscription_priority"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Title,
		arg.Handle,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.IsGiftcard,
		arg.Discountable,
		arg.OriginCountry,
		arg.Region,
		arg.Farm,
		arg.AltitudeMin,
		arg.AltitudeMax,
		arg.ProcessingMethod,
		arg.RoastLevel,
		arg.FlavorNotes,
		arg.Varietal,
		arg.HarvestDate,
		arg.WeightGrams,
		arg.LengthCm,
		arg.HeightCm,
		arg.WidthCm,
		arg.HsCode,
		arg.MidCode,
		arg.Material,
		arg.ExternalID,
		arg.ProductTypeID,
		arg.CollectionID,
		arg.Metadata,
		arg.SubscriptionEnabled,
		arg.SubscriptionIntervals,
		arg.MinSubscriptionQuantity,
		arg.MaxSubscriptionQuantity,
		arg.SubscriptionDiscountPercentage,
		arg.SubscriptionPriority,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const getProductByHandle = `-- name: GetProductByHandle :one
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE handle = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByHandle(ctx context.Context, handle string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByHandle, handle)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const getProductsByProcessingAndRoast = `-- name: GetProductsByProcessingAndRoast :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE processing_method = $1 AND roast_level = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetProductsByProcessingAndRoastParams struct {
	ProcessingMethod pgtype.Text `db:"processing_method" json:"processing_method"`
	RoastLevel       pgtype.Text `db:"roast_level" json:"roast_level"`
	Limit            int32       `db:"limit" json:"limit"`
	Offset           int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetProductsByProcessingAndRoast(ctx context.Context, arg GetProductsByProcessingAndRoastParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByProcessingAndRoast,
		arg.ProcessingMethod,
		arg.RoastLevel,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithinAltitudeRange = `-- name: GetProductsWithinAltitudeRange :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE altitude_min >= $1 AND altitude_max <= $2 AND deleted_at IS NULL
ORDER BY altitude_min ASC
LIMIT $3 OFFSET $4
`

type GetProductsWithinAltitudeRangeParams struct {
	AltitudeMin pgtype.Int4 `db:"altitude_min" json:"altitude_min"`
	AltitudeMax pgtype.Int4 `db:"altitude_max" json:"altitude_max"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetProductsWithinAltitudeRange(ctx context.Context, arg GetProductsWithinAltitudeRangeParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsWithinAltitudeRange,
		arg.AltitudeMin,
		arg.AltitudeMax,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscribableProduct = `-- name: GetSubscribableProduct :one
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE id = $1 AND subscription_enabled = true AND status = 'published' AND deleted_at IS NULL
`

func (q *Queries) GetSubscribableProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getSubscribableProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByOrigin = `-- name: ListProductsByOrigin :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE origin_country = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByOriginParams struct {
	OriginCountry pgtype.Text `db:"origin_country" json:"origin_country"`
	Limit         int32       `db:"limit" json:"limit"`
	Offset        int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListProductsByOrigin(ctx context.Context, arg ListProductsByOriginParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByOrigin, arg.OriginCountry, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByRoastLevel = `-- name: ListProductsByRoastLevel :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE roast_level = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByRoastLevelParams struct {
	RoastLevel pgtype.Text `db:"roast_level" json:"roast_level"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListProductsByRoastLevel(ctx context.Context, arg ListProductsByRoastLevelParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByRoastLevel, arg.RoastLevel, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListProductsByStatus(ctx context.Context, arg ListProductsByStatusParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySubscriptionInterval = `-- name: ListProductsBySubscriptionInterval :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE subscription_enabled = true 
    AND status = 'published' 
    AND $1 = ANY(subscription_intervals) 
    AND deleted_at IS NULL
ORDER BY subscription_priority DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsBySubscriptionIntervalParams struct {
	SubscriptionIntervals pq.StringArray `db:"subscription_intervals" json:"subscription_intervals"`
	Limit                 int32          `db:"limit" json:"limit"`
	Offset                int32          `db:"offset" json:"offset"`
}

func (q *Queries) ListProductsBySubscriptionInterval(ctx context.Context, arg ListProductsBySubscriptionIntervalParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySubscriptionInterval, arg.SubscriptionIntervals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribableProducts = `-- name: ListSubscribableProducts :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE subscription_enabled = true AND status = 'published' AND deleted_at IS NULL
ORDER BY subscription_priority DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscribableProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListSubscribableProducts(ctx context.Context, arg ListSubscribableProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listSubscribableProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority FROM products 
WHERE (
    title ILIKE '%' || $1 || '%' OR
    description ILIKE '%' || $1 || '%' OR
    origin_country ILIKE '%' || $1 || '%' OR
    region ILIKE '%' || $1 || '%' OR
    farm ILIKE '%' || $1 || '%' OR
    varietal ILIKE '%' || $1 || '%'
) AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Handle,
			&i.Subtitle,
			&i.Description,
			&i.Thumbnail,
			&i.Status,
			&i.IsGiftcard,
			&i.Discountable,
			&i.OriginCountry,
			&i.Region,
			&i.Farm,
			&i.AltitudeMin,
			&i.AltitudeMax,
			&i.ProcessingMethod,
			&i.RoastLevel,
			&i.FlavorNotes,
			&i.Varietal,
			&i.HarvestDate,
			&i.WeightGrams,
			&i.LengthCm,
			&i.HeightCm,
			&i.WidthCm,
			&i.HsCode,
			&i.MidCode,
			&i.Material,
			&i.ExternalID,
			&i.ProductTypeID,
			&i.CollectionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SubscriptionEnabled,
			&i.SubscriptionIntervals,
			&i.MinSubscriptionQuantity,
			&i.MaxSubscriptionQuantity,
			&i.SubscriptionDiscountPercentage,
			&i.SubscriptionPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    title = COALESCE($2, title),
    subtitle = COALESCE($3, subtitle),
    description = COALESCE($4, description),
    thumbnail = COALESCE($5, thumbnail),
    status = COALESCE($6, status),
    is_giftcard = COALESCE($7, is_giftcard),
    discountable = COALESCE($8, discountable),
    origin_country = COALESCE($9, origin_country),
    region = COALESCE($10, region),
    farm = COALESCE($11, farm),
    altitude_min = COALESCE($12, altitude_min),
    altitude_max = COALESCE($13, altitude_max),
    processing_method = COALESCE($14, processing_method),
    roast_level = COALESCE($15, roast_level),
    flavor_notes = COALESCE($16, flavor_notes),
    varietal = COALESCE($17, varietal),
    harvest_date = COALESCE($18, harvest_date),
    weight_grams = COALESCE($19, weight_grams),
    metadata = COALESCE($20, metadata),
    subscription_enabled = COALESCE($21, subscription_enabled),
    subscription_intervals = COALESCE($22, subscription_intervals),
    min_subscription_quantity = COALESCE($23, min_subscription_quantity),
    max_subscription_quantity = COALESCE($24, max_subscription_quantity),
    subscription_discount_percentage = COALESCE($25, subscription_discount_percentage),
    subscription_priority = COALESCE($26, subscription_priority),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority
`

type UpdateProductParams struct {
	ID                             pgtype.UUID      `db:"id" json:"id"`
	Title                          string           `db:"title" json:"title"`
	Subtitle                       pgtype.Text      `db:"subtitle" json:"subtitle"`
	Description                    pgtype.Text      `db:"description" json:"description"`
	Thumbnail                      pgtype.Text      `db:"thumbnail" json:"thumbnail"`
	Status                         string           `db:"status" json:"status"`
	IsGiftcard                     bool             `db:"is_giftcard" json:"is_giftcard"`
	Discountable                   bool             `db:"discountable" json:"discountable"`
	OriginCountry                  pgtype.Text      `db:"origin_country" json:"origin_country"`
	Region                         pgtype.Text      `db:"region" json:"region"`
	Farm                           pgtype.Text      `db:"farm" json:"farm"`
	AltitudeMin                    pgtype.Int4      `db:"altitude_min" json:"altitude_min"`
	AltitudeMax                    pgtype.Int4      `db:"altitude_max" json:"altitude_max"`
	ProcessingMethod               pgtype.Text      `db:"processing_method" json:"processing_method"`
	RoastLevel                     pgtype.Text      `db:"roast_level" json:"roast_level"`
	FlavorNotes                    pq.StringArray   `db:"flavor_notes" json:"flavor_notes"`
	Varietal                       pgtype.Text      `db:"varietal" json:"varietal"`
	HarvestDate                    pgtype.Date      `db:"harvest_date" json:"harvest_date"`
	WeightGrams                    pgtype.Int4      `db:"weight_grams" json:"weight_grams"`
	Metadata                       pgtype.JSONCodec `db:"metadata" json:"metadata"`
	SubscriptionEnabled            bool             `db:"subscription_enabled" json:"subscription_enabled"`
	SubscriptionIntervals          pq.StringArray   `db:"subscription_intervals" json:"subscription_intervals"`
	MinSubscriptionQuantity        pgtype.Int4      `db:"min_subscription_quantity" json:"min_subscription_quantity"`
	MaxSubscriptionQuantity        pgtype.Int4      `db:"max_subscription_quantity" json:"max_subscription_quantity"`
	SubscriptionDiscountPercentage pgtype.Numeric   `db:"subscription_discount_percentage" json:"subscription_discount_percentage"`
	SubscriptionPriority           pgtype.Int4      `db:"subscription_priority" json:"subscription_priority"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Thumbnail,
		arg.Status,
		arg.IsGiftcard,
		arg.Discountable,
		arg.OriginCountry,
		arg.Region,
		arg.Farm,
		arg.AltitudeMin,
		arg.AltitudeMax,
		arg.ProcessingMethod,
		arg.RoastLevel,
		arg.FlavorNotes,
		arg.Varietal,
		arg.HarvestDate,
		arg.WeightGrams,
		arg.Metadata,
		arg.SubscriptionEnabled,
		arg.SubscriptionIntervals,
		arg.MinSubscriptionQuantity,
		arg.MaxSubscriptionQuantity,
		arg.SubscriptionDiscountPercentage,
		arg.SubscriptionPriority,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE products SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority
`

type UpdateProductStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStatus, arg.ID, arg.Status)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const updateProductSubscriptionSettings = `-- name: UpdateProductSubscriptionSettings :one
UPDATE products SET
    subscription_intervals = $2,
    min_subscription_quantity = $3,
    max_subscription_quantity = $4,
    subscription_discount_percentage = $5,
    subscription_priority = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND subscription_enabled = true AND deleted_at IS NULL
RETURNING id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority
`

type UpdateProductSubscriptionSettingsParams struct {
	ID                             pgtype.UUID    `db:"id" json:"id"`
	SubscriptionIntervals          pq.StringArray `db:"subscription_intervals" json:"subscription_intervals"`
	MinSubscriptionQuantity        pgtype.Int4    `db:"min_subscription_quantity" json:"min_subscription_quantity"`
	MaxSubscriptionQuantity        pgtype.Int4    `db:"max_subscription_quantity" json:"max_subscription_quantity"`
	SubscriptionDiscountPercentage pgtype.Numeric `db:"subscription_discount_percentage" json:"subscription_discount_percentage"`
	SubscriptionPriority           pgtype.Int4    `db:"subscription_priority" json:"subscription_priority"`
}

func (q *Queries) UpdateProductSubscriptionSettings(ctx context.Context, arg UpdateProductSubscriptionSettingsParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductSubscriptionSettings,
		arg.ID,
		arg.SubscriptionIntervals,
		arg.MinSubscriptionQuantity,
		arg.MaxSubscriptionQuantity,
		arg.SubscriptionDiscountPercentage,
		arg.SubscriptionPriority,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}

const updateProductSubscriptionStatus = `-- name: UpdateProductSubscriptionStatus :one
UPDATE products SET
    subscription_enabled = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, handle, subtitle, description, thumbnail, status, is_giftcard, discountable, origin_country, region, farm, altitude_min, altitude_max, processing_method, roast_level, flavor_notes, varietal, harvest_date, weight_grams, length_cm, height_cm, width_cm, hs_code, mid_code, material, external_id, product_type_id, collection_id, metadata, created_at, updated_at, deleted_at, subscription_enabled, subscription_intervals, min_subscription_quantity, max_subscription_quantity, subscription_discount_percentage, subscription_priority
`

type UpdateProductSubscriptionStatusParams struct {
	ID                  pgtype.UUID `db:"id" json:"id"`
	SubscriptionEnabled bool        `db:"subscription_enabled" json:"subscription_enabled"`
}

func (q *Queries) UpdateProductSubscriptionStatus(ctx context.Context, arg UpdateProductSubscriptionStatusParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductSubscriptionStatus, arg.ID, arg.SubscriptionEnabled)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Handle,
		&i.Subtitle,
		&i.Description,
		&i.Thumbnail,
		&i.Status,
		&i.IsGiftcard,
		&i.Discountable,
		&i.OriginCountry,
		&i.Region,
		&i.Farm,
		&i.AltitudeMin,
		&i.AltitudeMax,
		&i.ProcessingMethod,
		&i.RoastLevel,
		&i.FlavorNotes,
		&i.Varietal,
		&i.HarvestDate,
		&i.WeightGrams,
		&i.LengthCm,
		&i.HeightCm,
		&i.WidthCm,
		&i.HsCode,
		&i.MidCode,
		&i.Material,
		&i.ExternalID,
		&i.ProductTypeID,
		&i.CollectionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SubscriptionEnabled,
		&i.SubscriptionIntervals,
		&i.MinSubscriptionQuantity,
		&i.MaxSubscriptionQuantity,
		&i.SubscriptionDiscountPercentage,
		&i.SubscriptionPriority,
	)
	return i, err
}
