// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (
    tenant_id,
    cart_id,
    product_sku_id,
    quantity,
    unit_price_cents
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (cart_id, product_sku_id)
DO UPDATE SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    updated_at = NOW()
RETURNING id, tenant_id, cart_id, product_sku_id, quantity, unit_price_cents, metadata, created_at, updated_at
`

type AddCartItemParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	CartID         pgtype.UUID `json:"cart_id"`
	ProductSkuID   pgtype.UUID `json:"product_sku_id"`
	Quantity       int32       `json:"quantity"`
	UnitPriceCents int32       `json:"unit_price_cents"`
}

// Add an item to cart (or update quantity if exists)
func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem,
		arg.TenantID,
		arg.CartID,
		arg.ProductSkuID,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CartID,
		&i.ProductSkuID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

// Remove all items from a cart
func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
    tenant_id,
    session_id,
    status,
    last_activity_at
) VALUES (
    $1, $2, 'active', NOW()
) RETURNING id, tenant_id, user_id, session_id, status, notes, metadata, last_activity_at, converted_to_order_id, expires_at, created_at, updated_at
`

type CreateCartParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

// Create a new cart for a session
func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.TenantID, arg.SessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.Notes,
		&i.Metadata,
		&i.LastActivityAt,
		&i.ConvertedToOrderID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT
    id,
    tenant_id,
    user_id,
    session_id,
    status,
    notes,
    metadata,
    last_activity_at,
    converted_to_order_id,
    expires_at,
    created_at,
    updated_at
FROM carts
WHERE id = $1
LIMIT 1
`

// Get cart by ID
func (q *Queries) GetCartByID(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.Notes,
		&i.Metadata,
		&i.LastActivityAt,
		&i.ConvertedToOrderID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartBySessionID = `-- name: GetCartBySessionID :one
SELECT
    id,
    tenant_id,
    user_id,
    session_id,
    status,
    notes,
    metadata,
    last_activity_at,
    converted_to_order_id,
    expires_at,
    created_at,
    updated_at
FROM carts
WHERE session_id = $1
  AND status = 'active'
LIMIT 1
`

// Get active cart for a session
func (q *Queries) GetCartBySessionID(ctx context.Context, sessionID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartBySessionID, sessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.Notes,
		&i.Metadata,
		&i.LastActivityAt,
		&i.ConvertedToOrderID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemCount = `-- name: GetCartItemCount :one
SELECT COALESCE(SUM(quantity), 0)::integer as item_count
FROM cart_items
WHERE cart_id = $1
`

// Get total number of items in cart
func (q *Queries) GetCartItemCount(ctx context.Context, cartID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCartItemCount, cartID)
	var item_count int32
	err := row.Scan(&item_count)
	return item_count, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT
    ci.id,
    ci.cart_id,
    ci.product_sku_id,
    ci.quantity,
    ci.unit_price_cents,
    ci.created_at,
    ci.updated_at,
    p.id as product_id,
    p.name as product_name,
    p.slug as product_slug,
    ps.sku,
    ps.weight_value,
    ps.weight_unit,
    ps.grind,
    ps.inventory_quantity,
    pi.url as image_url,
    pi.alt_text as image_alt
FROM cart_items ci
INNER JOIN product_skus ps ON ps.id = ci.product_sku_id
INNER JOIN products p ON p.id = ps.product_id
LEFT JOIN product_images pi ON pi.product_id = p.id AND pi.is_primary = TRUE
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC
`

type GetCartItemsRow struct {
	ID                pgtype.UUID        `json:"id"`
	CartID            pgtype.UUID        `json:"cart_id"`
	ProductSkuID      pgtype.UUID        `json:"product_sku_id"`
	Quantity          int32              `json:"quantity"`
	UnitPriceCents    int32              `json:"unit_price_cents"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProductID         pgtype.UUID        `json:"product_id"`
	ProductName       string             `json:"product_name"`
	ProductSlug       string             `json:"product_slug"`
	Sku               string             `json:"sku"`
	WeightValue       pgtype.Numeric     `json:"weight_value"`
	WeightUnit        string             `json:"weight_unit"`
	Grind             string             `json:"grind"`
	InventoryQuantity int32              `json:"inventory_quantity"`
	ImageUrl          pgtype.Text        `json:"image_url"`
	ImageAlt          pgtype.Text        `json:"image_alt"`
}

// Get all items in a cart with product details
func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductSkuID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSlug,
			&i.Sku,
			&i.WeightValue,
			&i.WeightUnit,
			&i.Grind,
			&i.InventoryQuantity,
			&i.ImageUrl,
			&i.ImageAlt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE cart_id = $1
  AND product_sku_id = $2
`

type RemoveCartItemParams struct {
	CartID       pgtype.UUID `json:"cart_id"`
	ProductSkuID pgtype.UUID `json:"product_sku_id"`
}

// Remove an item from cart
func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.CartID, arg.ProductSkuID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET
    quantity = $3,
    updated_at = NOW()
WHERE cart_id = $1
  AND product_sku_id = $2
`

type UpdateCartItemQuantityParams struct {
	CartID       pgtype.UUID `json:"cart_id"`
	ProductSkuID pgtype.UUID `json:"product_sku_id"`
	Quantity     int32       `json:"quantity"`
}

// Update quantity of a cart item
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCartItemQuantity, arg.CartID, arg.ProductSkuID, arg.Quantity)
	return err
}
