// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	Status             string             `json:"status"`
	Notes              pgtype.Text        `json:"notes"`
	Metadata           []byte             `json:"metadata"`
	LastActivityAt     pgtype.Timestamptz `json:"last_activity_at"`
	ConvertedToOrderID pgtype.UUID        `json:"converted_to_order_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CartItem struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CartID         pgtype.UUID        `json:"cart_id"`
	ProductSkuID   pgtype.UUID        `json:"product_sku_id"`
	Quantity       int32              `json:"quantity"`
	UnitPriceCents int32              `json:"unit_price_cents"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PriceList struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ListType    string             `json:"list_type"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PriceListEntry struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	PriceListID         pgtype.UUID        `json:"price_list_id"`
	ProductSkuID        pgtype.UUID        `json:"product_sku_id"`
	PriceCents          int32              `json:"price_cents"`
	CompareAtPriceCents pgtype.Int4        `json:"compare_at_price_cents"`
	IsAvailable         bool               `json:"is_available"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Description      pgtype.Text        `json:"description"`
	ShortDescription pgtype.Text        `json:"short_description"`
	Origin           pgtype.Text        `json:"origin"`
	Region           pgtype.Text        `json:"region"`
	Producer         pgtype.Text        `json:"producer"`
	Process          pgtype.Text        `json:"process"`
	RoastLevel       pgtype.Text        `json:"roast_level"`
	ElevationMin     pgtype.Int4        `json:"elevation_min"`
	ElevationMax     pgtype.Int4        `json:"elevation_max"`
	Variety          pgtype.Text        `json:"variety"`
	HarvestYear      pgtype.Int4        `json:"harvest_year"`
	TastingNotes     []string           `json:"tasting_notes"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	MetaTitle        pgtype.Text        `json:"meta_title"`
	MetaDescription  pgtype.Text        `json:"meta_description"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProductImage struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Url       string             `json:"url"`
	AltText   pgtype.Text        `json:"alt_text"`
	Width     pgtype.Int4        `json:"width"`
	Height    pgtype.Int4        `json:"height"`
	FileSize  pgtype.Int4        `json:"file_size"`
	SortOrder int32              `json:"sort_order"`
	IsPrimary bool               `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProductSku struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	Sku               string             `json:"sku"`
	WeightValue       pgtype.Numeric     `json:"weight_value"`
	WeightUnit        string             `json:"weight_unit"`
	Grind             string             `json:"grind"`
	BasePriceCents    int32              `json:"base_price_cents"`
	InventoryQuantity int32              `json:"inventory_quantity"`
	InventoryPolicy   string             `json:"inventory_policy"`
	LowStockThreshold pgtype.Int4        `json:"low_stock_threshold"`
	IsActive          bool               `json:"is_active"`
	WeightGrams       pgtype.Int4        `json:"weight_grams"`
	RequiresShipping  bool               `json:"requires_shipping"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	Token     string             `json:"token"`
	Data      []byte             `json:"data"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Email        string             `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Website      pgtype.Text        `json:"website"`
	BusinessName pgtype.Text        `json:"business_name"`
	TaxID        pgtype.Text        `json:"tax_id"`
	Settings     []byte             `json:"settings"`
	Status       string             `json:"status"`
	TrialEndsAt  pgtype.Timestamptz `json:"trial_ends_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
