// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_configs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderConfig = `-- name: CreateProviderConfig :one
INSERT INTO tenant_provider_configs (
    tenant_id,
    type,
    name,
    is_active,
    is_default,
    priority,
    config_encrypted
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at
`

type CreateProviderConfigParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Type            string      `json:"type"`
	Name            string      `json:"name"`
	IsActive        bool        `json:"is_active"`
	IsDefault       bool        `json:"is_default"`
	Priority        int32       `json:"priority"`
	ConfigEncrypted string      `json:"config_encrypted"`
}

// Creates a new tenant provider configuration.
// If is_default is true, this will be the default provider for this type.
// The config_encrypted field should contain base64-encoded AES-256-GCM encrypted JSON.
func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) (TenantProviderConfig, error) {
	row := q.db.QueryRow(ctx, createProviderConfig,
		arg.TenantID,
		arg.Type,
		arg.Name,
		arg.IsActive,
		arg.IsDefault,
		arg.Priority,
		arg.ConfigEncrypted,
	)
	var i TenantProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.Priority,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShippingRate = `-- name: CreateShippingRate :one
INSERT INTO tenant_shipping_rates (
    tenant_id,
    provider_config_id,
    service_code,
    service_name,
    origin_postal_code,
    destination_postal_code,
    weight_grams,
    rate_cents,
    currency,
    valid_until,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, provider_config_id, service_code, service_name, origin_postal_code, destination_postal_code, weight_grams, rate_cents, currency, valid_until, metadata, created_at
`

type CreateShippingRateParams struct {
	TenantID              pgtype.UUID        `json:"tenant_id"`
	ProviderConfigID      pgtype.UUID        `json:"provider_config_id"`
	ServiceCode           string             `json:"service_code"`
	ServiceName           string             `json:"service_name"`
	OriginPostalCode      pgtype.Text        `json:"origin_postal_code"`
	DestinationPostalCode string             `json:"destination_postal_code"`
	WeightGrams           int32              `json:"weight_grams"`
	RateCents             int32              `json:"rate_cents"`
	Currency              string             `json:"currency"`
	ValidUntil            pgtype.Timestamptz `json:"valid_until"`
	Metadata              []byte             `json:"metadata"`
}

// Creates a new shipping rate (manual or cached from provider).
// For manual rates, valid_until should be NULL.
// For provider-cached rates, valid_until should be a future timestamp.
func (q *Queries) CreateShippingRate(ctx context.Context, arg CreateShippingRateParams) (TenantShippingRate, error) {
	row := q.db.QueryRow(ctx, createShippingRate,
		arg.TenantID,
		arg.ProviderConfigID,
		arg.ServiceCode,
		arg.ServiceName,
		arg.OriginPostalCode,
		arg.DestinationPostalCode,
		arg.WeightGrams,
		arg.RateCents,
		arg.Currency,
		arg.ValidUntil,
		arg.Metadata,
	)
	var i TenantShippingRate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderConfigID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.OriginPostalCode,
		&i.DestinationPostalCode,
		&i.WeightGrams,
		&i.RateCents,
		&i.Currency,
		&i.ValidUntil,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredShippingRates = `-- name: DeleteExpiredShippingRates :exec
DELETE FROM tenant_shipping_rates
WHERE valid_until IS NOT NULL AND valid_until < NOW()
`

// Deletes shipping rates that have expired across ALL tenants.
// IMPORTANT: This is a system-wide cleanup job. Only call from background worker
// context, never from tenant-scoped handlers. For tenant-specific cleanup,
// use DeleteExpiredShippingRatesForTenant instead.
func (q *Queries) DeleteExpiredShippingRates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredShippingRates)
	return err
}

const deleteExpiredShippingRatesForTenant = `-- name: DeleteExpiredShippingRatesForTenant :exec
DELETE FROM tenant_shipping_rates
WHERE tenant_id = $1
    AND valid_until IS NOT NULL
    AND valid_until < NOW()
`

// Deletes expired shipping rates for a specific tenant.
// Use this when cleaning up in a tenant-scoped context.
func (q *Queries) DeleteExpiredShippingRatesForTenant(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredShippingRatesForTenant, tenantID)
	return err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :exec
DELETE FROM tenant_provider_configs
WHERE id = $1 AND tenant_id = $2
`

type DeleteProviderConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Deletes a provider configuration.
// Cascades to tenant_shipping_rates if this is a shipping provider.
func (q *Queries) DeleteProviderConfig(ctx context.Context, arg DeleteProviderConfigParams) error {
	_, err := q.db.Exec(ctx, deleteProviderConfig, arg.ID, arg.TenantID)
	return err
}

const deleteShippingRate = `-- name: DeleteShippingRate :exec
DELETE FROM tenant_shipping_rates
WHERE id = $1 AND tenant_id = $2
`

type DeleteShippingRateParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Deletes a specific shipping rate.
func (q *Queries) DeleteShippingRate(ctx context.Context, arg DeleteShippingRateParams) error {
	_, err := q.db.Exec(ctx, deleteShippingRate, arg.ID, arg.TenantID)
	return err
}

const deleteShippingRatesByProvider = `-- name: DeleteShippingRatesByProvider :exec
DELETE FROM tenant_shipping_rates
WHERE tenant_id = $1 AND provider_config_id = $2
`

type DeleteShippingRatesByProviderParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	ProviderConfigID pgtype.UUID `json:"provider_config_id"`
}

// Deletes all shipping rates for a specific provider config.
// Used when removing a shipping provider configuration.
func (q *Queries) DeleteShippingRatesByProvider(ctx context.Context, arg DeleteShippingRatesByProviderParams) error {
	_, err := q.db.Exec(ctx, deleteShippingRatesByProvider, arg.TenantID, arg.ProviderConfigID)
	return err
}

const getActiveProviderConfigs = `-- name: GetActiveProviderConfigs :many
SELECT id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at FROM tenant_provider_configs
WHERE tenant_id = $1
    AND type = $2
    AND is_active = TRUE
ORDER BY is_default DESC, priority ASC
`

type GetActiveProviderConfigsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     string      `json:"type"`
}

// Retrieves all active provider configurations for a tenant and type.
// Results are ordered by is_default DESC (default first), then priority ASC (lower priority number first).
// Used by registry to load the best provider for a tenant.
func (q *Queries) GetActiveProviderConfigs(ctx context.Context, arg GetActiveProviderConfigsParams) ([]TenantProviderConfig, error) {
	rows, err := q.db.Query(ctx, getActiveProviderConfigs, arg.TenantID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantProviderConfig{}
	for rows.Next() {
		var i TenantProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Name,
			&i.IsActive,
			&i.IsDefault,
			&i.Priority,
			&i.ConfigEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultProviderConfig = `-- name: GetDefaultProviderConfig :one
SELECT id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at FROM tenant_provider_configs
WHERE tenant_id = $1
    AND type = $2
    AND is_default = TRUE
    AND is_active = TRUE
`

type GetDefaultProviderConfigParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     string      `json:"type"`
}

// Retrieves the default provider configuration for a tenant and type.
// Returns error if no default is configured.
func (q *Queries) GetDefaultProviderConfig(ctx context.Context, arg GetDefaultProviderConfigParams) (TenantProviderConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultProviderConfig, arg.TenantID, arg.Type)
	var i TenantProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.Priority,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at FROM tenant_provider_configs
WHERE id = $1 AND tenant_id = $2
`

type GetProviderConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Retrieves a specific provider configuration by ID.
// Used to load configuration for a known provider config.
func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (TenantProviderConfig, error) {
	row := q.db.QueryRow(ctx, getProviderConfig, arg.ID, arg.TenantID)
	var i TenantProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.Priority,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingRate = `-- name: GetShippingRate :one
SELECT id, tenant_id, provider_config_id, service_code, service_name, origin_postal_code, destination_postal_code, weight_grams, rate_cents, currency, valid_until, metadata, created_at FROM tenant_shipping_rates
WHERE tenant_id = $1
    AND destination_postal_code = $2
    AND weight_grams = $3
    AND (valid_until IS NULL OR valid_until > NOW())
ORDER BY created_at DESC
LIMIT 1
`

type GetShippingRateParams struct {
	TenantID              pgtype.UUID `json:"tenant_id"`
	DestinationPostalCode string      `json:"destination_postal_code"`
	WeightGrams           int32       `json:"weight_grams"`
}

// Retrieves a cached shipping rate for a specific route and weight.
// Only returns rates that are still valid (valid_until is NULL or in future).
func (q *Queries) GetShippingRate(ctx context.Context, arg GetShippingRateParams) (TenantShippingRate, error) {
	row := q.db.QueryRow(ctx, getShippingRate, arg.TenantID, arg.DestinationPostalCode, arg.WeightGrams)
	var i TenantShippingRate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderConfigID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.OriginPostalCode,
		&i.DestinationPostalCode,
		&i.WeightGrams,
		&i.RateCents,
		&i.Currency,
		&i.ValidUntil,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getShippingRatesByProvider = `-- name: GetShippingRatesByProvider :many
SELECT id, tenant_id, provider_config_id, service_code, service_name, origin_postal_code, destination_postal_code, weight_grams, rate_cents, currency, valid_until, metadata, created_at FROM tenant_shipping_rates
WHERE tenant_id = $1
    AND provider_config_id = $2
ORDER BY service_code, destination_postal_code, weight_grams
`

type GetShippingRatesByProviderParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	ProviderConfigID pgtype.UUID `json:"provider_config_id"`
}

// Retrieves all shipping rates for a specific provider config.
// Used to show manual rates configured for a tenant.
func (q *Queries) GetShippingRatesByProvider(ctx context.Context, arg GetShippingRatesByProviderParams) ([]TenantShippingRate, error) {
	rows, err := q.db.Query(ctx, getShippingRatesByProvider, arg.TenantID, arg.ProviderConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantShippingRate{}
	for rows.Next() {
		var i TenantShippingRate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderConfigID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.OriginPostalCode,
			&i.DestinationPostalCode,
			&i.WeightGrams,
			&i.RateCents,
			&i.Currency,
			&i.ValidUntil,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at FROM tenant_provider_configs
WHERE tenant_id = $1
    AND ($2::VARCHAR IS NULL OR type = $2)
ORDER BY type, is_default DESC, priority ASC
`

type ListProviderConfigsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     pgtype.Text `json:"type"`
}

// Lists all provider configurations for a tenant, optionally filtered by type.
// Used in admin UI to show all configured providers.
// If type is empty string, returns all types.
func (q *Queries) ListProviderConfigs(ctx context.Context, arg ListProviderConfigsParams) ([]TenantProviderConfig, error) {
	rows, err := q.db.Query(ctx, listProviderConfigs, arg.TenantID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantProviderConfig{}
	for rows.Next() {
		var i TenantProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Name,
			&i.IsActive,
			&i.IsDefault,
			&i.Priority,
			&i.ConfigEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultProvider = `-- name: UnsetDefaultProvider :exec
UPDATE tenant_provider_configs
SET is_default = FALSE, updated_at = NOW()
WHERE tenant_id = $1 AND type = $2 AND is_default = TRUE
`

type UnsetDefaultProviderParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     string      `json:"type"`
}

// Removes is_default flag from all providers of a given type for a tenant.
// Used before setting a new default provider.
func (q *Queries) UnsetDefaultProvider(ctx context.Context, arg UnsetDefaultProviderParams) error {
	_, err := q.db.Exec(ctx, unsetDefaultProvider, arg.TenantID, arg.Type)
	return err
}

const updateProviderConfig = `-- name: UpdateProviderConfig :one
UPDATE tenant_provider_configs
SET
    name = COALESCE($3, name),
    is_active = COALESCE($4, is_active),
    is_default = COALESCE($5, is_default),
    priority = COALESCE($6, priority),
    config_encrypted = COALESCE($7, config_encrypted),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, type, name, is_active, is_default, priority, config_encrypted, created_at, updated_at
`

type UpdateProviderConfigParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	Name            pgtype.Text `json:"name"`
	IsActive        pgtype.Bool `json:"is_active"`
	IsDefault       pgtype.Bool `json:"is_default"`
	Priority        pgtype.Int4 `json:"priority"`
	ConfigEncrypted pgtype.Text `json:"config_encrypted"`
}

// Updates an existing provider configuration.
// Note: Changing is_default requires handling the previous default.
func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) (TenantProviderConfig, error) {
	row := q.db.QueryRow(ctx, updateProviderConfig,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IsActive,
		arg.IsDefault,
		arg.Priority,
		arg.ConfigEncrypted,
	)
	var i TenantProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.IsActive,
		&i.IsDefault,
		&i.Priority,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
