// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ProcessingMethod.
const (
	Honey      ProcessingMethod = "honey"
	Natural    ProcessingMethod = "natural"
	Other      ProcessingMethod = "other"
	SemiWashed ProcessingMethod = "semi_washed"
	Washed     ProcessingMethod = "washed"
)

// Defines values for ProductStatus.
const (
	Draft     ProductStatus = "draft"
	Published ProductStatus = "published"
	Rejected  ProductStatus = "rejected"
)

// Defines values for RoastLevel.
const (
	Dark        RoastLevel = "dark"
	Light       RoastLevel = "light"
	Medium      RoastLevel = "medium"
	MediumDark  RoastLevel = "medium_dark"
	MediumLight RoastLevel = "medium_light"
)

// Defines values for SubscriptionInterval.
const (
	Annually     SubscriptionInterval = "annually"
	Bimonthly    SubscriptionInterval = "bimonthly"
	Biweekly     SubscriptionInterval = "biweekly"
	Monthly      SubscriptionInterval = "monthly"
	Quarterly    SubscriptionInterval = "quarterly"
	Semiannually SubscriptionInterval = "semiannually"
	Weekly       SubscriptionInterval = "weekly"
)

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	AltitudeMax                    *int                    `json:"altitude_max,omitempty"`
	AltitudeMin                    *int                    `json:"altitude_min,omitempty"`
	CollectionId                   *openapi_types.UUID     `json:"collection_id,omitempty"`
	Description                    *string                 `json:"description,omitempty"`
	Discountable                   *bool                   `json:"discountable,omitempty"`
	ExternalId                     *string                 `json:"external_id,omitempty"`
	Farm                           *string                 `json:"farm,omitempty"`
	FlavorNotes                    *[]string               `json:"flavor_notes,omitempty"`
	Handle                         string                  `json:"handle"`
	HarvestDate                    *openapi_types.Date     `json:"harvest_date,omitempty"`
	HeightCm                       *float64                `json:"height_cm,omitempty"`
	HsCode                         *string                 `json:"hs_code,omitempty"`
	IsGiftcard                     *bool                   `json:"is_giftcard,omitempty"`
	LengthCm                       *float64                `json:"length_cm,omitempty"`
	Material                       *string                 `json:"material,omitempty"`
	MaxSubscriptionQuantity        *int                    `json:"max_subscription_quantity,omitempty"`
	Metadata                       *map[string]interface{} `json:"metadata,omitempty"`
	MidCode                        *string                 `json:"mid_code,omitempty"`
	MinSubscriptionQuantity        *int                    `json:"min_subscription_quantity,omitempty"`
	OriginCountry                  *string                 `json:"origin_country,omitempty"`
	ProcessingMethod               *ProcessingMethod       `json:"processing_method,omitempty"`
	ProductTypeId                  *openapi_types.UUID     `json:"product_type_id,omitempty"`
	Region                         *string                 `json:"region,omitempty"`
	RoastLevel                     *RoastLevel             `json:"roast_level,omitempty"`
	Status                         *ProductStatus          `json:"status,omitempty"`
	SubscriptionDiscountPercentage *float64                `json:"subscription_discount_percentage,omitempty"`
	SubscriptionEnabled            *bool                   `json:"subscription_enabled,omitempty"`
	SubscriptionIntervals          *[]SubscriptionInterval `json:"subscription_intervals,omitempty"`
	SubscriptionPriority           *int                    `json:"subscription_priority,omitempty"`
	Subtitle                       *string                 `json:"subtitle,omitempty"`
	Thumbnail                      *string                 `json:"thumbnail,omitempty"`
	Title                          string                  `json:"title"`
	Varietal                       *string                 `json:"varietal,omitempty"`
	WeightGrams                    *int                    `json:"weight_grams,omitempty"`
	WidthCm                        *float64                `json:"width_cm,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *map[string]interface{} `json:"details,omitempty"`
	Error   string                  `json:"error"`
	Message string                  `json:"message"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// ProcessingMethod defines model for ProcessingMethod.
type ProcessingMethod string

// Product defines model for Product.
type Product struct {
	AltitudeMax  *int                `json:"altitude_max"`
	AltitudeMin  *int                `json:"altitude_min"`
	CollectionId *openapi_types.UUID `json:"collection_id"`
	CreatedAt    time.Time           `json:"created_at"`
	Description  *string             `json:"description"`
	Discountable bool                `json:"discountable"`
	ExternalId   *string             `json:"external_id"`
	Farm         *string             `json:"farm"`
	FlavorNotes  *[]string           `json:"flavor_notes,omitempty"`
	Handle       string              `json:"handle"`
	HarvestDate  *openapi_types.Date `json:"harvest_date"`
	HeightCm     *float64            `json:"height_cm"`
	HsCode       *string             `json:"hs_code"`
	Id           openapi_types.UUID  `json:"id"`
	IsGiftcard   bool                `json:"is_giftcard"`
	LengthCm     *float64            `json:"length_cm"`
	Material     *string             `json:"material"`

	// MaxSubscriptionQuantity Maximum quantity for subscription orders (null = no limit)
	MaxSubscriptionQuantity *int                    `json:"max_subscription_quantity"`
	Metadata                *map[string]interface{} `json:"metadata"`
	MidCode                 *string                 `json:"mid_code"`

	// MinSubscriptionQuantity Minimum quantity for subscription orders
	MinSubscriptionQuantity *int                `json:"min_subscription_quantity,omitempty"`
	OriginCountry           *string             `json:"origin_country"`
	ProcessingMethod        *ProcessingMethod   `json:"processing_method,omitempty"`
	ProductTypeId           *openapi_types.UUID `json:"product_type_id"`
	Region                  *string             `json:"region"`
	RoastLevel              *RoastLevel         `json:"roast_level,omitempty"`
	Status                  ProductStatus       `json:"status"`

	// SubscriptionDiscountPercentage Percentage discount applied to subscription orders
	SubscriptionDiscountPercentage *float64 `json:"subscription_discount_percentage,omitempty"`

	// SubscriptionEnabled Whether this product can be purchased as a subscription
	SubscriptionEnabled bool `json:"subscription_enabled"`

	// SubscriptionIntervals Available subscription intervals for this product
	SubscriptionIntervals *[]SubscriptionInterval `json:"subscription_intervals,omitempty"`

	// SubscriptionPriority Priority for displaying in subscription lists (higher = more prominent)
	SubscriptionPriority *int      `json:"subscription_priority,omitempty"`
	Subtitle             *string   `json:"subtitle"`
	Thumbnail            *string   `json:"thumbnail"`
	Title                string    `json:"title"`
	UpdatedAt            time.Time `json:"updated_at"`
	Varietal             *string   `json:"varietal"`
	WeightGrams          *int      `json:"weight_grams"`
	WidthCm              *float64  `json:"width_cm"`
}

// ProductStatus defines model for ProductStatus.
type ProductStatus string

// RoastLevel defines model for RoastLevel.
type RoastLevel string

// SubscriptionInterval defines model for SubscriptionInterval.
type SubscriptionInterval string

// UpdateProductRequest defines model for UpdateProductRequest.
type UpdateProductRequest struct {
	AltitudeMax                    *int                    `json:"altitude_max,omitempty"`
	AltitudeMin                    *int                    `json:"altitude_min,omitempty"`
	Description                    *string                 `json:"description,omitempty"`
	Discountable                   *bool                   `json:"discountable,omitempty"`
	Farm                           *string                 `json:"farm,omitempty"`
	FlavorNotes                    *[]string               `json:"flavor_notes,omitempty"`
	HarvestDate                    *openapi_types.Date     `json:"harvest_date,omitempty"`
	IsGiftcard                     *bool                   `json:"is_giftcard,omitempty"`
	MaxSubscriptionQuantity        *int                    `json:"max_subscription_quantity,omitempty"`
	Metadata                       *map[string]interface{} `json:"metadata,omitempty"`
	MinSubscriptionQuantity        *int                    `json:"min_subscription_quantity,omitempty"`
	OriginCountry                  *string                 `json:"origin_country,omitempty"`
	ProcessingMethod               *ProcessingMethod       `json:"processing_method,omitempty"`
	Region                         *string                 `json:"region,omitempty"`
	RoastLevel                     *RoastLevel             `json:"roast_level,omitempty"`
	Status                         *ProductStatus          `json:"status,omitempty"`
	SubscriptionDiscountPercentage *float64                `json:"subscription_discount_percentage,omitempty"`
	SubscriptionEnabled            *bool                   `json:"subscription_enabled,omitempty"`
	SubscriptionIntervals          *[]SubscriptionInterval `json:"subscription_intervals,omitempty"`
	SubscriptionPriority           *int                    `json:"subscription_priority,omitempty"`
	Subtitle                       *string                 `json:"subtitle,omitempty"`
	Thumbnail                      *string                 `json:"thumbnail,omitempty"`
	Title                          *string                 `json:"title,omitempty"`
	Varietal                       *string                 `json:"varietal,omitempty"`
	WeightGrams                    *int                    `json:"weight_grams,omitempty"`
}

// UpdateSubscriptionRequest defines model for UpdateSubscriptionRequest.
type UpdateSubscriptionRequest struct {
	MaxSubscriptionQuantity        *int                    `json:"max_subscription_quantity,omitempty"`
	MinSubscriptionQuantity        *int                    `json:"min_subscription_quantity,omitempty"`
	SubscriptionDiscountPercentage *float64                `json:"subscription_discount_percentage,omitempty"`
	SubscriptionEnabled            *bool                   `json:"subscription_enabled,omitempty"`
	SubscriptionIntervals          *[]SubscriptionInterval `json:"subscription_intervals,omitempty"`
	SubscriptionPriority           *int                    `json:"subscription_priority,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error            string `json:"error"`
	Message          string `json:"message"`
	ValidationErrors []struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"validation_errors"`
}

// LimitParam defines model for LimitParam.
type LimitParam = int

// PageParam defines model for PageParam.
type PageParam = int

// ProductIdParam defines model for ProductIdParam.
type ProductIdParam = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	// Page Page number (1-based)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Status Filter by product status
	Status *ProductStatus `form:"status,omitempty" json:"status,omitempty"`

	// OriginCountry Filter by origin country
	OriginCountry *string `form:"origin_country,omitempty" json:"origin_country,omitempty"`

	// RoastLevel Filter by roast level
	RoastLevel *RoastLevel `form:"roast_level,omitempty" json:"roast_level,omitempty"`

	// ProcessingMethod Filter by processing method
	ProcessingMethod *ProcessingMethod `form:"processing_method,omitempty" json:"processing_method,omitempty"`

	// Subscribable Filter to only subscribable products
	Subscribable *bool `form:"subscribable,omitempty" json:"subscribable,omitempty"`

	// SubscriptionInterval Filter by supported subscription interval
	SubscriptionInterval *SubscriptionInterval `form:"subscription_interval,omitempty" json:"subscription_interval,omitempty"`
}

// SearchProductsParams defines parameters for SearchProducts.
type SearchProductsParams struct {
	// Q Search query
	Q string `form:"q" json:"q"`

	// Page Page number (1-based)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSubscribableProductsParams defines parameters for ListSubscribableProducts.
type ListSubscribableProductsParams struct {
	// Page Page number (1-based)
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Interval Filter by subscription interval
	Interval *SubscriptionInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProductRequest

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProductRequest

// UpdateProductSubscriptionJSONRequestBody defines body for UpdateProductSubscription for application/json ContentType.
type UpdateProductSubscriptionJSONRequestBody = UpdateSubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List products
	// (GET /products)
	ListProducts(ctx echo.Context, params ListProductsParams) error
	// Create product
	// (POST /products)
	CreateProduct(ctx echo.Context) error
	// Search products
	// (GET /products/search)
	SearchProducts(ctx echo.Context, params SearchProductsParams) error
	// List subscribable products
	// (GET /products/subscribable)
	ListSubscribableProducts(ctx echo.Context, params ListSubscribableProductsParams) error
	// Delete product
	// (DELETE /products/{id})
	DeleteProduct(ctx echo.Context, id ProductIdParam) error
	// Get product
	// (GET /products/{id})
	GetProduct(ctx echo.Context, id ProductIdParam) error
	// Update product
	// (PATCH /products/{id})
	UpdateProduct(ctx echo.Context, id ProductIdParam) error
	// Update product subscription settings
	// (PATCH /products/{id}/subscription)
	UpdateProductSubscription(ctx echo.Context, id ProductIdParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProducts converts echo context to params.
func (w *ServerInterfaceWrapper) ListProducts(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProductsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "origin_country" -------------

	err = runtime.BindQueryParameter("form", true, false, "origin_country", ctx.QueryParams(), &params.OriginCountry)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter origin_country: %s", err))
	}

	// ------------- Optional query parameter "roast_level" -------------

	err = runtime.BindQueryParameter("form", true, false, "roast_level", ctx.QueryParams(), &params.RoastLevel)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter roast_level: %s", err))
	}

	// ------------- Optional query parameter "processing_method" -------------

	err = runtime.BindQueryParameter("form", true, false, "processing_method", ctx.QueryParams(), &params.ProcessingMethod)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter processing_method: %s", err))
	}

	// ------------- Optional query parameter "subscribable" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscribable", ctx.QueryParams(), &params.Subscribable)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscribable: %s", err))
	}

	// ------------- Optional query parameter "subscription_interval" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_interval", ctx.QueryParams(), &params.SubscriptionInterval)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscription_interval: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProducts(ctx, params)
	return err
}

// CreateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProduct(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProduct(ctx)
	return err
}

// SearchProducts converts echo context to params.
func (w *ServerInterfaceWrapper) SearchProducts(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchProductsParams
	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, true, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchProducts(ctx, params)
	return err
}

// ListSubscribableProducts converts echo context to params.
func (w *ServerInterfaceWrapper) ListSubscribableProducts(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSubscribableProductsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "interval" -------------

	err = runtime.BindQueryParameter("form", true, false, "interval", ctx.QueryParams(), &params.Interval)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSubscribableProducts(ctx, params)
	return err
}

// DeleteProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProduct(ctx, id)
	return err
}

// GetProduct converts echo context to params.
func (w *ServerInterfaceWrapper) GetProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProduct(ctx, id)
	return err
}

// UpdateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProduct(ctx, id)
	return err
}

// UpdateProductSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProductSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProductSubscription(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/products", wrapper.ListProducts)
	router.POST(baseURL+"/products", wrapper.CreateProduct)
	router.GET(baseURL+"/products/search", wrapper.SearchProducts)
	router.GET(baseURL+"/products/subscribable", wrapper.ListSubscribableProducts)
	router.DELETE(baseURL+"/products/:id", wrapper.DeleteProduct)
	router.GET(baseURL+"/products/:id", wrapper.GetProduct)
	router.PATCH(baseURL+"/products/:id", wrapper.UpdateProduct)
	router.PATCH(baseURL+"/products/:id/subscription", wrapper.UpdateProductSubscription)

}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse ValidationError

type ListProductsRequestObject struct {
	Params ListProductsParams
}

type ListProductsResponseObject interface {
	VisitListProductsResponse(w http.ResponseWriter) error
}

type ListProducts200JSONResponse struct {
	Pagination *PaginationMeta `json:"pagination,omitempty"`
	Products   *[]Product      `json:"products,omitempty"`
}

func (response ListProducts200JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProducts400JSONResponse struct{ BadRequestJSONResponse }

func (response ListProducts400JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListProducts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProducts401JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProductRequestObject struct {
	Body *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201JSONResponse Product

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProduct400JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateProduct401JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreateProduct422JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SearchProductsRequestObject struct {
	Params SearchProductsParams
}

type SearchProductsResponseObject interface {
	VisitSearchProductsResponse(w http.ResponseWriter) error
}

type SearchProducts200JSONResponse struct {
	Pagination *PaginationMeta `json:"pagination,omitempty"`
	Products   *[]Product      `json:"products,omitempty"`
}

func (response SearchProducts200JSONResponse) VisitSearchProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchProducts400JSONResponse struct{ BadRequestJSONResponse }

func (response SearchProducts400JSONResponse) VisitSearchProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListSubscribableProductsRequestObject struct {
	Params ListSubscribableProductsParams
}

type ListSubscribableProductsResponseObject interface {
	VisitListSubscribableProductsResponse(w http.ResponseWriter) error
}

type ListSubscribableProducts200JSONResponse struct {
	Pagination *PaginationMeta `json:"pagination,omitempty"`
	Products   *[]Product      `json:"products,omitempty"`
}

func (response ListSubscribableProducts200JSONResponse) VisitListSubscribableProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSubscribableProducts400JSONResponse struct{ BadRequestJSONResponse }

func (response ListSubscribableProducts400JSONResponse) VisitListSubscribableProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProductRequestObject struct {
	Id ProductIdParam `json:"id"`
}

type DeleteProductResponseObject interface {
	VisitDeleteProductResponse(w http.ResponseWriter) error
}

type DeleteProduct204Response struct {
}

func (response DeleteProduct204Response) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteProduct401JSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteProduct404JSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProductRequestObject struct {
	Id ProductIdParam `json:"id"`
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response GetProduct400JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProduct404JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductRequestObject struct {
	Id   ProductIdParam `json:"id"`
	Body *UpdateProductJSONRequestBody
}

type UpdateProductResponseObject interface {
	VisitUpdateProductResponse(w http.ResponseWriter) error
}

type UpdateProduct200JSONResponse Product

func (response UpdateProduct200JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProduct400JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProduct401JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProduct404JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdateProduct422JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductSubscriptionRequestObject struct {
	Id   ProductIdParam `json:"id"`
	Body *UpdateProductSubscriptionJSONRequestBody
}

type UpdateProductSubscriptionResponseObject interface {
	VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error
}

type UpdateProductSubscription200JSONResponse Product

func (response UpdateProductSubscription200JSONResponse) VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductSubscription400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProductSubscription400JSONResponse) VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductSubscription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProductSubscription401JSONResponse) VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProductSubscription404JSONResponse) VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductSubscription422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpdateProductSubscription422JSONResponse) VisitUpdateProductSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List products
	// (GET /products)
	ListProducts(ctx context.Context, request ListProductsRequestObject) (ListProductsResponseObject, error)
	// Create product
	// (POST /products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// Search products
	// (GET /products/search)
	SearchProducts(ctx context.Context, request SearchProductsRequestObject) (SearchProductsResponseObject, error)
	// List subscribable products
	// (GET /products/subscribable)
	ListSubscribableProducts(ctx context.Context, request ListSubscribableProductsRequestObject) (ListSubscribableProductsResponseObject, error)
	// Delete product
	// (DELETE /products/{id})
	DeleteProduct(ctx context.Context, request DeleteProductRequestObject) (DeleteProductResponseObject, error)
	// Get product
	// (GET /products/{id})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
	// Update product
	// (PATCH /products/{id})
	UpdateProduct(ctx context.Context, request UpdateProductRequestObject) (UpdateProductResponseObject, error)
	// Update product subscription settings
	// (PATCH /products/{id}/subscription)
	UpdateProductSubscription(ctx context.Context, request UpdateProductSubscriptionRequestObject) (UpdateProductSubscriptionResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListProducts operation middleware
func (sh *strictHandler) ListProducts(ctx echo.Context, params ListProductsParams) error {
	var request ListProductsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProducts(ctx.Request().Context(), request.(ListProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProducts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProductsResponseObject); ok {
		return validResponse.VisitListProductsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(ctx echo.Context) error {
	var request CreateProductRequestObject

	var body CreateProductJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx.Request().Context(), request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		return validResponse.VisitCreateProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchProducts operation middleware
func (sh *strictHandler) SearchProducts(ctx echo.Context, params SearchProductsParams) error {
	var request SearchProductsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchProducts(ctx.Request().Context(), request.(SearchProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchProducts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchProductsResponseObject); ok {
		return validResponse.VisitSearchProductsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListSubscribableProducts operation middleware
func (sh *strictHandler) ListSubscribableProducts(ctx echo.Context, params ListSubscribableProductsParams) error {
	var request ListSubscribableProductsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListSubscribableProducts(ctx.Request().Context(), request.(ListSubscribableProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSubscribableProducts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListSubscribableProductsResponseObject); ok {
		return validResponse.VisitListSubscribableProductsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProduct operation middleware
func (sh *strictHandler) DeleteProduct(ctx echo.Context, id ProductIdParam) error {
	var request DeleteProductRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProduct(ctx.Request().Context(), request.(DeleteProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteProductResponseObject); ok {
		return validResponse.VisitDeleteProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(ctx echo.Context, id ProductIdParam) error {
	var request GetProductRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx.Request().Context(), request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		return validResponse.VisitGetProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProduct operation middleware
func (sh *strictHandler) UpdateProduct(ctx echo.Context, id ProductIdParam) error {
	var request UpdateProductRequestObject

	request.Id = id

	var body UpdateProductJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProduct(ctx.Request().Context(), request.(UpdateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProductResponseObject); ok {
		return validResponse.VisitUpdateProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProductSubscription operation middleware
func (sh *strictHandler) UpdateProductSubscription(ctx echo.Context, id ProductIdParam) error {
	var request UpdateProductSubscriptionRequestObject

	request.Id = id

	var body UpdateProductSubscriptionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProductSubscription(ctx.Request().Context(), request.(UpdateProductSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProductSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProductSubscriptionResponseObject); ok {
		return validResponse.VisitUpdateProductSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe2/cNhL/KgTv/mgBrb27sdPWQIFLn+dD2jPi5oq7IFjMSqMVU4lUSMqxL9jvfiCp",
	"F7XclexsHofmL1sSH8N5/PibIfctjUVRCo5cK3rxlpYgoUCN0j49ZQXTV+aVeUpQxZKVmglOL+ivVbFG",
	"SURKmMZCkRIlKWGDNKLMfH9dobyjEeVQIL2guRmKRlTFGRbghkuhyjW9WM4jWsAtK6qCXizm5onx+imi",
	"+q40/RnXuEFJt9uIXsEG90hlPhHuRPtiMVuDwuTLPSLV0gYkWoyLIEVSxfoy2SeH+06eP7/8oZm+BJ11",
	"s7OERlTi64pJTOiFlhX2ZcFbKMrcNFwsH+HZ+eOvZvj1N+vZYpk8msHZ+ePZ2fLx48XZ4quz+XxOI5oK",
	"WYCmF7Sq7NC10EpLxjd0a4SWqErBFVrbfgfJM3xdodLmKRZcI7f/QlnmLAazkNNXyqzmbU+uv0pM6QX9",
	"y2nnN6fuqzr9UUoh3VS+Nr6DhMh6sm1EfxX6J1Hx5P1P/AyVqGSMhAtNUjvnNqLPOVQ6E5L9Fz+ADE8q",
	"nSHX9aikNfk2ov+CnCX2tet9LFmG4wak6poQrNs07mfd43uJoLF2456jlFKUKDVzTgS5ZrpKcFXArXlu",
	"o2a+GzVRrzXj461jkecYGwlXzJppxMMHK3wb+M5ULCquYW0CqxfvLvjq9mshcgRuOuCtRskhrwUo4PYp",
	"8o3OapjamSAFWQwaLs/PQw1zuBFyxYV2erQQGpS5fgFSwp15zoAnTvrRSTKQN6j0KgGNnv7si1AHZJtM",
	"r+LCby0qo68oZC6HtLavWsUi2REspCWmVhuW6hhk4lkhhVwFzZDb0R4mVwEaJYN8kv0KuF2pat160ep1",
	"BVwzfed56yLkrQVqSEDb0IQkYaY75Fe9aPGcTKxfYWzBsGDJZM0VjO+Xb+ruFVEh2YbxlY0FeTdJM6UU",
	"MSrF+GZVoM5EMgZBV22HX1x7N4hBk5UZfWpMS9zU4TwqoxSg9CrHG8zHpHtmmj61LQ3sadCVmrAiI/21",
	"a2y69S3RYMuqRBkj14Zb9I0yj0KeG2Y9IT/2JkNuIGxi9Hg9jRfIG8h91Dm07Ote98u6dwiYvGlKyYQc",
	"+mUQ5VW11kxPRDSdVcWaA8t915Es5DnTh70ByVBPxIg3DiQ3EpzuDm9ib1jyMOTa9snhi3oxLfy/DABJ",
	"SyH8LTpBDczZ+164hM1wHRPlQq8ciQphEypVO33Xo6HBHf3aJab+Qt203XChlV7BhnHLXX5Bh7j+kl2u",
	"0RdkOR/DxHIo+yiKalG7TNflPBzFw04rM5nyun59uONASXXm0uRUThJ/8KDehphsJOBmyhf0DagME5ue",
	"6Era4TLB0aRLCgu2ar8LnaE0w3dWbr/tOEVt/3Hi2FlqOYRCXuW5Y2yepx7glZ1Bvr7/YKO0c88Q3aJj",
	"S52TFfg+SJfz5dlsvpgtzn9bzC8ezS/m8//0EzdDy2aaFTiB23ajPiFraRCJAE+Iwe8cb0ks0hSRvGE6",
	"I5Zkmjx9jXIDhdARybEQPLI9XoEqGMeTKQs7Nn8enbDh091qv88wjzPMkfwOKmN8Q8x+bJQS7eD8+PAD",
	"Ft5O84I2ujJRZpRFI1pryhgHYZazPyw4PYS5d8tBnTFRMuCzOyY3EGeYpjgzEZrjzNG0wMJGmf7Q55az",
	"xfnQ06YY3EsIPDA9vJftGTiYLXSyzr+ZL06WixNbzhhQ4VFRnYcdu2ryrslKb2s4OX9nrfVzmV5IuFhf",
	"I3DlK25akB1MevyiwS+Or5KmBUmFJP2+RMgEpSJfmFnJt4QLYjepL6m/m47D8NR8qtXDWxqbL2ldMVEm",
	"ioXcAGexsTMwudISEhu0cVWWJpVRsZBm8/3K8NCyzBm2aEB/YBJjTWwfIjF3o2asNNLtkX9SVjdukKlZ",
	"3sA4Tr+jxqH3Tw87Z/uxBqyHONqHyiFHBelyym5h/+7w9yFr+9Rzz0F1um1Hmr7EVhsxIVrscZoOy+Z7",
	"sOz42awv9u8ZGvJJdMYUqR2BxMDJGklZyTgDhQkBRcBbAr1fVjyo3t4As6b3tdL2sFHWF6ivqRe0EFxn",
	"uWHRa/YG8Y/8ziMNHyzxHp5OuFZW+ISpMoc7w6UY91eZM6UV+SJjG6P2b0khJJp1Gh7ELagfTui78Hpq",
	"KaqNEsdK01xIyB05fQh380oB3TyZ1qW6OD2NE37iSLCdk/HNSSyK09pG6jRIvE5elRuPE9jCwrgou8tt",
	"YJKTHq6Qa8vryD8n87qqTI6fSfSrHd2Qf0cmcyGKh4DfsCTSjvro7N7pV79g0mXH70yeBgm043p+TaXF",
	"Yp/0DdKePdjlZX2e4fYk4j0472XhiYTU9C+rdc7qpFqi6YaJn3P3W+wYpLfF9AbPjZVsaSVhVbHyH7v3",
	"Ccg/zKrNH2/KpsPOdEGk6tcWHPD1MDDygLH7/3UFUqPMm7IDcF5Bbh/bfz2Zuq47Uj23NviYJ1j3PY/a",
	"3aU+yIHSPU+JBhnRrtAf5xSFP3TOj3Ua8n9+svFe+N+nd3rxJzux2AZiywFpX5N70fRdQv/hEfzZXfe6",
	"a8iegVsnvhUDRz83bZ9VCizH6UdAta+QbgSyf4TeNFYIX3O+lCnDfFD0axjdNMl+M60JU92VnLHDKTfl",
	"4cMp31Qjp1uhFe8OagyOcWVsfG0cxa1/jSBRPqlM4DdPPzVe/o/ff2uutlkPtV+79Zk0yd0KYjwVzb0j",
	"cCc1WFi8olCyv+3mUN0Ntrrw+Kz+SJ5cXZLrqiyF1HT3FtTVpc02C+CwMa3rI4omI4tIM4l5lbIclTug",
	"wFksisLEMjHWr4t7LVjuSPFj1/7J1aXRMErlZFiczE/mdssvkUPJ6AV9dDI/eWQIN+jMarVNEc3DBvVu",
	"ReAZasnwBgmQ0h1EYmIzZSLS4aqoncsJfZnYPFjpq+5j/7rlizA0dE1Ou3uP22i0ce/upmntr+EnlmuU",
	"ZH3XllG63CdwU7L9OO362YBPHJrekS/SkK/w9AOGFr4m2atM7gTx/vldRcIxq/Dkfe41VQF9Ejai/JoW",
	"kppH7rmpusM372GKAfHcK48WRPD8rqkArW3Rq+fIQcfotfVkGu6Mh7SgHGZgEi6xHZ7a32kn6yW80W5f",
	"Di7JLufze13K9Heosr2nMGom/0ZDV+eeTh2ao/bQFjTcT7ZR+Lqy2QoduBlbxMZz0srk3NuInjlVhERo",
	"VXbau1RsuyzGu3iXce1WVxUFmETMgmXfAzVs7LFO++qlUZRQAZB211cJEI5vBqC8g8neVdf6UjYq/Z1I",
	"7o52Izd4nXbr0wOT2m53HHBxNBlaD9lrf1IXsT6S8SN6tlyOd9q93dx3mtrynbEDXrONun3+VCHIONu7",
	"3V/bz8ON3RWxIbkBHmNCUgtmZrcZOpfrvn/LD07WQF0I915P/NmAu0TQbLB4cHd8X7zjzwqntRklqirX",
	"6kEB5Pl0Pd5hKPSdur8xjzLZ1quhPe0aHh4Hmex1b5ZPitXeh0h85g7v6OwhvnhMIrHLCfZR1LGoeMuS",
	"rQuDHDUGsF6kmriPBMZoww+2XUcb7un1/g/IAt5ztv9XZU7EkGofsue6mQ53an+y5VvD6eDwZhuNptGq",
	"xJilLB5o3ASy/fWcr/efUb8/pc8/JNs6Mtl+uBl/Rj1mwxK0I0n+UlxtmAAneMtcAWYkbLxjueNY8Ph0",
	"PXh2OImuf1AHqo+ZPx5dv5/PHYXf1x43nd8b0D/1qIzdXg+5s0cfYsFTtqlkXbsWksA057726dMn7Oih",
	"s51Px9v70hGF2qCM+uz72nfTRjF7IqJ3hmDdr3968OKlcS+F8iaclda2cbOYRjSilcx7162gZKHrVjeL",
	"AEu/1u4AYM9Qyn2eHRjyZbvEnbKPTyDsYQMWxjn7tVSnlO3L7f8CAAD//6QKgjz+QAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
