# config/prometheus/prometheus.yml
# Prometheus Configuration for Coffee E-commerce

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "coffee-app"
    static_configs:
      - targets: ["app:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 15s

  - job_name: "valkey"
    static_configs:
      - targets: ["valkey:6379"]
    scrape_interval: 10s

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: "/metrics"
    scrape_interval: 10s
