services:
  freyja:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
      - nats
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/freyja_db
      - NATS_URL=nats://nats:4222
  
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freyja_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
  
  nats:
    image: nats:2.9.15-alpine
    ports:
      - "4222:4222"  # Client port
      - "8222:8222"  # HTTP monitoring port
      - "6222:6222"  # Cluster port
    command: ["-js", "-m", "8222"]  # Enable JetStream and monitoring
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  pgadmin_data: